#!/usr/bin/env sh
pushd /Applications/aws-mturk-clt-1.3.1/bin
./grantBonus.sh -workerid A1CX53BTI88Z12 -amount 1.65 -assignment 3I33IC7ZWF2J4KSL6MPRDYFK8FHA22 -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A345O1LUQZLTSL -amount 1.7 -assignment 3R2PKQ87NW8OH6FCSS0O95H1RS2MI8 -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A351OM98GNHTOK -amount 1.9 -assignment 3ZR9AIQJUB9X6L9QIYBMH705J8P04N -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A3S81UFDOWF2ST -amount 2.1 -assignment 3Z2R0DQ0JHEMUX9XMRRD9H5BTV3E2R -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A2YPWT2UKHWRN0 -amount 1.9 -assignment 3S4AW7T80BIA3HYC7RX5FRSTM5C4LA -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A2NOR6R1M1NHGX -amount 1.8 -assignment 379J5II41OGSVJV5WX9IOD4KZU5ELP -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A3PD4Q4287A2G8 -amount 2.05 -assignment 3GNCZX450INFWRTR8K039BNDJP8PA3 -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A3FURNEHDNA7AR -amount 1.85 -assignment 3PPTZCWALQK1XB2EKPVRQ94WX61ZQ5 -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A1JXSNKXAXT9OU -amount 2.05 -assignment 37TD41K0AH902Y6HKF0OABIC6DQSCG -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A3PAKJN12UK49T -amount 2.05 -assignment 3S0TNUHWKTISO6XM6DPUDQ0TFJW8DX -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A33249GFIAKI1G -amount 2.3 -assignment 3EWIJTFFVO7FYN6J74NZQTCWWXL0EV -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A2MU4C3CB1EL7O -amount 2.1 -assignment 3FIJLY1B6U4ASIAZJ0MVNCY4G6CFPZ -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid AWSXWPJJPYFMN -amount 1.95 -assignment 304SM51WA34HSTEB6F4TZRCUOSQSB9 -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
./grantBonus.sh -workerid A1JR4SLSKZQO9K -amount 2.15 -assignment 3J2UYBXQQLCBL8D41M41E5KJFZY60H -reason "Your bonus for performing my hit. My deepest apologies for being so late. Some unavoidable conflicts came up. I added $1.50 to your hit as compensation." 
popd