#!/usr/bin/env sh
pushd /Applications/aws-mturk-clt-1.3.1/bin
./grantBonus.sh -workerid A32CIL5S21Y4MR -amount 1.85 -assignment 3TEM0PF1Q5XA6HSJB9CFKBUBV4D0DW -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A26CQZGNV3GJXS -amount 1.75 -assignment 3EA3QWIZ4IVSU15W1P10VJCTKKGTI1 -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A2658LN9LNAR1D -amount 1.0 -assignment 3TUI152ZZBN42FH6CEMZYFKKJB71Q4 -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A2OG7XGWOX5ZEF -amount 1.85 -assignment 30MVJZJNHMD55XGOL1HJGKQH3TPJ9S -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A00236363DL2ZN8A4FD78 -amount 1.6 -assignment 36V4Q8R5ZK01Y43V505XI78NHNPMQM -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A2Y5DDEPG81LLJ -amount 1.85 -assignment 3TY7ZAOG5FKIKNYT3QY2OOP1FEWK0H -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A1945USNZHTROX -amount 1.45 -assignment 3VNL7UK1XFJ8KA360HVFSMZ14SOTFA -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid AUQTHU5AOZVQC -amount 2.1 -assignment 39JEC7537U1GUQNLEA5TLY2J410CVO -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A3F7TD3W9043EO -amount 2.9 -assignment 3G5W44VEU7IFVR9EHSN59GCHMVKGKF -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A3HQXCWOIQKT4F -amount 1.6 -assignment 3KGTPGBS6XL3JT6JCR6IDZREE3DU27 -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid AAJEPFSQNC6X -amount 3.6 -assignment 3AQF3RZ558I2ICSU44NMHC7NKKEF6M -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A2BN2BM2ZGA9Z5 -amount 1.35 -assignment 3E4GGUZ1T8RPGX17ID2G7CIGCCGK21 -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A2JAXR0JNTQOMA -amount 1.8 -assignment 3EJJQNKU9R5FIRHKRIEKVSAWWM7RHW -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A1IV8V08K6S98Y -amount 1.95 -assignment 3E1QT0TDFP99WHD8YRQ54NG667W8IS -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A1SWC3GHKGILLF -amount 2.2 -assignment 34S6N1K2ZVJ4FTM7MYHO9G1XQV3HLJ -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A1G69P73SBVUR4 -amount 1.35 -assignment 373ERPL3YO85N08FRCV99BDK7HNRTT -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A14PFRHG0A2YY9 -amount 2.95 -assignment 3WS1NTTKEYC7416F2F758BXW7HSF0L -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid AGDJB8B8CDZ71 -amount 1.35 -assignment 3WT783CTPBH1LCPF9TETKM8C19KCBI -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A2KRI49I1CXKZO -amount 0.85 -assignment 3IUZPWIU1O7BSDZEWXRNVJY5GJAWKU -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A1OV86I0FAFAM1 -amount 2.5 -assignment 3KV0LJBBH2L1A5IVIFUXNXISD9QRMR -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid ATV65PFDODC08 -amount 1.55 -assignment 3U0SRXB7CD57SN3VUG9X0C7SIZ0RNR -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A2VLGTBAQB3C62 -amount 1.2 -assignment 3HL8HNGX451P0VUS2BQY1MYPAM99FG -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid AUQAQE2HHMJAZ -amount 2.05 -assignment 3X4MXAO0BGOXFHC9MH0KWVKJBB5RWJ -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A2R2L2GA314OEI -amount 1.6 -assignment 3DL65MZB8DFZSF1ZJKGJLUEX46XCEI -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A1A7P5LC80G47W -amount 0.95 -assignment 31EUONYN2V3H3FKO4FEKGYW0TFJOVX -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A15XKRYWZFJHKF -amount 1.55 -assignment 3EJJQNKU9R5FIRHKRIEKVSAWWNRRHI -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A3G2JDGJCXCWVD -amount 1.75 -assignment 31LVTDXBL7AH4N0AI3TINK33D40RLP -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid A2SVQGQWXAJ4YA -amount 1.1 -assignment 3HMVI3QICJSDBH8S3O3TB1NMIKOY14 -reason "Your bonus for performing my hit. Congratulations on your performance!" 
./grantBonus.sh -workerid APY5RHG4STNP1 -amount 1.55 -assignment 3ZSY5X72NXBPA837VV9AF17X895RO6 -reason "Your bonus for performing my hit. Congratulations on your performance!" 
popd